package com.example.springstudentwebapp.controller;

import com.example.springstudentwebapp.model.Student;
import com.example.springstudentwebapp.repository.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@RestController
public class StudentRestController {

    @Autowired
    StudentRepository studentRepository;

    @GetMapping("/")
    public List<Student> students() {
        List<Student> studentList = studentRepository.findAll();
        return studentList;
    }

    @GetMapping("/addstudent")
    public List<Student> addStudent() {
        Student std = new Student();
        std.setBornTime(LocalTime.now());
        std.setBorn(LocalDate.now());
        List<Student> lst = studentRepository.findAll();
        std.setName("Autogenerated size = " + lst.size());
        studentRepository.save(std);
        System.out.println("Student save = " + std.getName());
        return lst;
    }

}
